### ISSUE TITLE
Every team member to create PR, review at least one merge, merge at least one PR. Also create one issue

### ISSUE THREAD

**Issue by DaveyJH** [DaveyJH/holiday-hamper#1]
- [x] Dave
  - [x] Create PR #6
  - [x] Review #54
  - [x] Merge #54
  - [x] Issue #2 
- [x] Mike
  - [x] Create PR #92
  - [x] Review #70
  - [x] Merge #70
  - [x] Issue #7 
- [x] Polycarp
  - [x] Create PR #65
  - [x] Review 6effb3d
  - [x] Merge 6effb3d
  - [x] Issue #95
- [x] Mateusz
  - [x] Create PR #24
  - [x] Review 6514ba7
  - [x] Merge 6514ba7
  - [x] Issue #23
- [x] Karol
  - [x] Create PR #91
  - [x] Review #92
  - [x] Merge #92
  - [x] Issue #27 
- [x] Abi
  - [x] Create PR #54
  - [x] Review a8163bb
  - [x] Merge a8163bb
  - [x] Issue #5

**Comment by DaveyJH** [comment]
#6 Dave create PR

**Comment by DaveyJH** [comment]
a8163bb Abi review and merge

**Comment by Abibubble** [comment]
#5 I created this issue
