### ISSUE TITLE
Decide team name

### ISSUE THREAD

**Issue by DaveyJH** [DaveyJH/holiday-hamper#2]
Please add potential names to this issue

- Christmas Crackers

**Comment by mateuszniechwiej** [comment]
Christmas Crackers sounds good to me 👍

**Comment by MikeAvgeros** [comment]
Christmas Crackers sounds good to me too!

**Comment by DaveyJH** [comment]
Holiday hackers

**Comment by Abibubble** [comment]
Fan of Holiday Hackers 👍

**Comment by KarMiles** [comment]
Holiday Hackers sounds great and fun! :D

**Comment by MikeAvgeros** [comment]
Holiday Hackers sounds good to me and I would like to also suggest Holiday Hoppers.

**Comment by DaveyJH** [comment]
Happy Holiday Hackers

Decided in slack call
