### ISSUE TITLE
Fix overflow issue when window is resized after loading

### ISSUE THREAD

**Issue by Abibubble** [DaveyJH/holiday-hamper#213]
window.addEventListener("resize", //remove stars here)

**Comment by DaveyJH** [comment]
The bug is due to the stars being generated dynamically and absolutely using px. My mistake. Could change the x position of them to something like `${Math.random() * 75vw + 7.5}vw` (to avoid left edge overflow/disappearing)

The team can discuss the preferred action and resolve accordingly.
