### ISSUE TITLE
Design ideas & inspirations

### ISSUE THREAD

**Issue by mateuszniechwiej** [DaveyJH/holiday-hamper#23]
<div align="center">
  Site design ideas and websites links we can get inspiration from
</div>
<hr>

 Some sites and ideas we can use:

1. * link: https://nationaltoday.com/religious-holidays/
    * comment: Use the calendar to mark the holidays. We could also take a similar approach to filter holidays by religion to put them as menu links in the header.
  
2. * link: https://study.soas.ac.uk/religious-holidays-of-the-world/
    * comment: some short description of holidays we can use and choose from(and credit this page) for our site.

**Comment by mateuszniechwiej** [comment]
https://www.whychristmas.com/

**Comment by MikeAvgeros** [comment]
https://decemberinmadeira.madeirabelongstoall.com/ Although this website looks like it's incomplete and abandoned, it makes me thing of let's say having a full width image of each holiday with a tag in the middle and then a button on the side to learn more about this holiday and an arrow down which takes you to another holiday. If you click on the learn more button, it will start an animation to fade out the full width image and fade in some text, another image and some links to additional resources. The arrow will scroll the page down to another full width image and tag of another holiday. Perhaps, we can also add an animation to move the text in place or something along those lines. Take full advantage of css and javascript.

**Comment by KarMiles** [comment]
I see there are a few Christmas/holiday-themed icons available on Font Awesome that we could use. 
https://fontawesome.com/v5.15/icons?d=gallery&p=2&q=christmas&m=free , 
https://fontawesome.com/v5.15/icons?d=gallery&p=2&q=holiday&m=free

**Comment by MikeAvgeros** [comment]
Another design idea would be a starry night and then some stars would light up when you hover over them and a text will appear below the star with the name of the holiday so you can click on it and we can have some animation transitioning to a page with info about said holiday. And in the contact form we can say something like help us fill the sky with more holidays blabla. I like the backgrounds on this website, they are cute. https://www.actionforchildren.org.uk/support-us/make-a-donation/appeals/secret-santa/ so we can use something the night sky of the second page.

**Comment by MikeAvgeros** [comment]
Also, this may not be as suitable but I stumbled across this site just now and I remember Dave talked about having boxes with images and text next to it on each celebration. If you scroll down on this site https://electricgamebox.com/ you can see these cropped boxed that have another small box next to it. We can have nicely cropped boxed with the name of the holiday and some information and a learn more button and the small box next to it can be a video about this holiday. I'm sure we can find some relevant video on youtube about each holiday.

**Comment by DaveyJH** [comment]
![image](https://user-images.githubusercontent.com/80708826/145468217-422a0c7b-3392-43b2-9008-e05904c6ad68.png)
I do quite like this style (not the angular design, but the box in box type style)

**Comment by DaveyJH** [comment]
![image](https://user-images.githubusercontent.com/80708826/145471441-53e9c058-9a49-4826-a0bb-abd542443a9a.png)

I like the simplicity of this design and will try and knock up a wireframe around this idea

**Comment by DaveyJH** [comment]
https://patternico.com/
content page backgrounds
