### ISSUE TITLE
README: User stories

### ISSUE THREAD

**Issue by KarMiles** [DaveyJH/holiday-hamper#27]
Visitor stories
Owner stories

**Comment by DaveyJH** [comment]
> As a new user, I want to know what the site is about
>
> As a user, I want a little information about each holiday so I can choose which one to investigate further
>
> As a site owner, I want to provide a platform to educate users about the various holidays celebrated throughout the world

**Comment by Abibubble** [comment]
This issue is included in the README #12 issue
