### ISSUE TITLE
Decide on project name

### ISSUE THREAD

**Issue by DaveyJH** [DaveyJH/holiday-hamper#3]
Please add project name here when app has been chosen

**Comment by DaveyJH** [comment]
## Holiday Hamper

I like this as I think it suggests a variety of things 'inside' (different holidays)
The contents of hampers are usually small and 'bite-size' = no cognitive overload
Alliteration is always a win 😀
Hampers are transportable - so is the website and its information

**Comment by KarMiles** [comment]
Sounds great! And we could probably use hints of the hamper in  the graphical side of the site.

**Comment by MikeAvgeros** [comment]
I am happy with this name. And as Karol suggested, we can maybe add some festive hampers on the design.

**Comment by Abibubble** [comment]
Sounds awesome!!

**Comment by mateuszniechwiej** [comment]
Happy with Holiday Hamper :raised_hand:

**Comment by DaveyJH** [comment]
# Holiday Hamper

Decided on slack call
