### ISSUE TITLE
README: Design

### ISSUE THREAD

**Issue by Abibubble** [DaveyJH/holiday-hamper#46]

**Comment by KarMiles** [comment]
Just an idea for fonts available on Google Fonts that seem festive (a bit old-school but not too old-fashioned): Eczar and Lobster
![image](https://user-images.githubusercontent.com/89101012/145671517-4794336a-f13d-49a8-8ca0-14de7ecc9598.png)
![image](https://user-images.githubusercontent.com/89101012/145671548-a9500264-8134-4d5e-9bb6-5d2dd765ecd1.png)
