### ISSUE TITLE
README: Bugs

### ISSUE THREAD

**Issue by Abibubble** [DaveyJH/holiday-hamper#52]

**Comment by DaveyJH** [comment]
> One bug we came across yesterday was having all the js logic in one file, which we added in all the html document. This threw errors when js couldn't find specific elements that were not present in all the html files. We resolved it by splitting the code and importing only what's necessary in the html files.

**Comment by DaveyJH** [comment]
Stars were appearing above header and nav bar
@MikeAvgeros fixed I think. Could you add comments to explain how?

**Comment by mateuszniechwiej** [comment]
Fetching quiz data from json file:
Bug:
Couldn't fetch data from json file
404 ERROR
Solution:
Moving file to public folder( asset folder) from JS- folder.

- [x] Resolved
