### ISSUE TITLE
Decide on the tech stack for the application

### ISSUE THREAD

**Issue by MikeAvgeros** [DaveyJH/holiday-hamper#7]

**Comment by mateuszniechwiej** [comment]
Suggestions:
- HTML/CSS/JS(vanilla/JQuery)
- Python flask with MongoDB (if we need to use DB)?
- Bootstrap - CSS Framework
#7

**Comment by DaveyJH** [comment]
- I like the idea of learning about React if we think it isn't too much to achieve in the time frame.
- I am not the biggest fan of bootstrap but happy to work with it if we feel the benefits are substantial.
- DB may not be necessary, we need to target a few MVPs first - I think that will help us decide
- I haven't worked with JQuery at all but again, more than happy to learn

*For me, HTML (possibly with a template file that gets content added in for each holiday), CSS, JS are essential, everything else depends on the MVPs*

Beyond those tech stacks, I have very little experience but I learn pretty quickly and am pretty comfortable with fault finding

**Comment by MikeAvgeros** [comment]
- If the team wants to use React, I can guide you. I've used it a few of times in my job and I practiced deploying a fake project this morning on GitHub pages (as I've actually never deployed a React project before). Having said that, it's good if you have a basic knowledge of how it works and of course a good knowledge of Javascript, otherwise, we may have to narrow down the scope to make it on time. If we do use React, we can use a CSS library for React called Material-UI. It will speed things up. 

- If we don't use React, let's focus on vanilla HTML/CSS/Javascript. We can use CSS grid for the layout. We could use some library like Materialize or Bootstrap for some elements to speed things up. Doing everything from scratch is a bit tiring. I don't recommend using jQuery for the reason that it's deprecated and although it kind of speed things up, it's not likely that you will actually use it professionally, only on legacy code.

- I highly recommend we focus on the frontend for now, meet our milestones and if time allows, we'll make a new branch and create a backend for the site. For the backend, we can use Python or Javascript and Mongo as our DB.

**Comment by Abibubble** [comment]
I have very limited knowledge of React, so could do React, although that may end up being more difficult than it needs to be (especially as Jim keeps mentioning not to go too crazy with tech stacks).

I wouldn't mind using a CSS framework, but Bootstrap is a nightmare I'd rather avoid, and Materialize is about to be deprecated. We could choose another framework, or we could use SCSS for a bit of fun, or just vanilla.

I don't think we'll need backend for our site at all, unless we're adding in extra features that we haven't mentioned already - so far, everything can be done with a JS object or json file. And it's definitely not worth adding a backend in, if we have no need for it

**Comment by DaveyJH** [comment]
Possible API for content.

**Comment by MikeAvgeros** [comment]
One thing that was talked about in the meeting was to potentially use html/javascript in the same way that you would use React or a templating language. We can add our metatags, header and footer in the index.html page and then for the main content we can have an empty div with an id and then use javascript to dynamically add/change content there. The content can come from a json file and if we have time we can even put that in an API and it can be a small attempt at making a backend in the hope it will give us more points. It's not such a common way of designing a page I guess but it might be fun and it will mean we will write more "javascript" than html. Of course, once we have the final wireframe / design layout and know all the features that we will add, this will possibly dictate the way we will do it.
